import os

os.makedirs("knowledge_base", exist_ok=True)

kb_docs = {
    "doc_01_eligibility.txt": "Loan eligibility criteria vary by loan type based on income, employment stability, and age. Personal loans require a stable monthly income and a minimum age of 21 years. Home and auto loans evaluate collateral value alongside the applicant's debt-to-income ratio. Education and business loans require admission proof or business registration documents respectively.",
    "doc_02_emi.txt": "EMI calculation rules depend on the principal loan amount, annual interest rate, and total tenure in months. The formula uses standard reducing balance amortization to compute monthly installments. Any missed payments attract additional penal interest charges and late fees. Pre-equated monthly installment dates are fixed on the fifth of every calendar month.",
    "doc_03_fees.txt": "Credit-card fee structure includes annual membership charges, cash advance fees, and foreign currency markup rates. Annual fees can be waived if the annual retail spending crosses a specified threshold limit. Late payment charges are levied progressively based on the outstanding statement balance. GST at eighteen percent is applicable on all banking service fees.",
    "doc_04_kyc.txt": "KYC document requirements mandate valid government-issued photo identification and address proof. Accepted documents include an Aadhaar card, PAN card, passport, or recent utility bills. In-person verification or digital video KYC must be completed before account activation. Failure to update KYC details leads to temporary account freeze restrictions.",
    "doc_05_fraud.txt": "Fraud-dispute resolution process begins immediately upon customer reporting unauthorized transactions. A temporary credit is issued while the internal risk team investigates the flagged activity. Resolution timelines range from seven to forty-five working days depending on merchant cooperation. Confirmed fraudulent transactions result in permanent chargebacks and account security resets.",
    "doc_06_closure.txt": "Account-closure process requires a written application submitted by the primary account holder. All pending dues, outstanding loan balances, and accrued fees must be cleared prior to closure. The bank processes settlement refunds within seven working days after verification. No closure charges are applicable if the account has remained active for over one year.",
    "doc_07_interest.txt": "Interest-rate slabs are categorized based on borrower risk profiles and credit bureau scores. Higher credit scores qualify applicants for lower preferential interest rate tiers. Floating interest rates are pegged to the benchmark lending rate and adjusted quarterly. Fixed interest rates remain constant throughout the entire agreed loan tenure.",
    "doc_08_prepayment.txt": "Prepayment-penalty rules govern partial or full early settlement of active loan accounts. Floating-rate retail loans carry zero prepayment penalties as per regulatory guidelines. Fixed-rate or corporate loans may attract a nominal closure fee ranging from one to three percent. Prepayments are automatically adjusted against the principal outstanding balance.",
    "doc_09_balance.txt": "Minimum-balance requirements specify the average monthly balance to be maintained in savings accounts. Non-compliance results in non-maintenance service charges debited at the end of the quarter. Premium account tiers require higher balance thresholds but offer waived banking fees. Balance computations are based on daily closing ledger figures.",
    "doc_10_credit_score.txt": "Credit-score impact factors include repayment history, credit utilization ratio, and hard inquiries. Timely EMI and credit card bill payments positively improve the bureau score over time. High credit utilization exceeding thirty percent negatively impacts creditworthiness. Frequent loan applications trigger multiple hard inquiries that temporarily lower the score.",
    "doc_11_joint_account.txt": "Joint-account rules allow two or more individuals to operate a single banking account. Operating mandates can be configured as either 'Either or Survivor' or 'Jointly'. All account holders share equal legal liability for any overdrafts or outstanding loan obligations. Addition or removal of joint holders requires signed consent from all existing parties.",
    "doc_12_nri.txt": "NRI-account eligibility is restricted to non-resident Indians maintaining NRE, NRO, or FCNR accounts. Applicants must provide valid passport copies, overseas residential proof, and valid visa documents. Repatriation rules differ across account types regarding foreign currency transfers. Domestic loan facilities for NRIs require an Indian resident co-applicant."
}

for filename, content in kb_docs.items():
    with open(os.path.join("knowledge_base", filename), "w", encoding="utf-8") as f:
        f.write(content)

print(f"Successfully generated {len(kb_docs)} knowledge base documents in 'knowledge_base/' directory.")